<MyRoot>:

    randomLabel: randomLabel

    BoxLayout:
        orientation: "vertical"
        Label:
            text: "AppDiProva"
            font_size: 64
            color: 1, 0, 0
        Label:
            id: randomLabel
            text: "-"
            font_size: 64
        Button:
            text: "Generate"
            font_size: 32
            size: 100, 50
            on_press: root.generate_number()
